# Generated by Django 3.1.7 on 2021-03-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('songName', models.CharField(blank=True, max_length=100, null=True)),
                ('songDurationSeconds', models.PositiveIntegerField()),
                ('uploadedTime', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
