# Generated by Django 3.1.7 on 2021-03-13 06:14

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('songFileServer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('audiobookTitle', models.CharField(max_length=100, null=True)),
                ('titleAuthor', models.CharField(max_length=100, null=True)),
                ('audiobookNarrator', models.CharField(max_length=100, null=True)),
                ('audiobookDurationSeconds', models.PositiveIntegerField(null=True)),
                ('uploadedTime', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('podcastName', models.CharField(max_length=100, null=True)),
                ('podcastDurationSeconds', models.PositiveIntegerField(null=True)),
                ('uploadedTime', models.DateTimeField(null=True)),
                ('podcastHost', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=99)),
                ('podcastParticipants', django_mysql.models.ListCharField(models.CharField(max_length=99), max_length=1000, null=True, size=10)),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='songDurationSeconds',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='songName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='uploadedTime',
            field=models.DateTimeField(null=True),
        ),
    ]
