# Generated by Django 3.1.7 on 2021-03-13 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songFileServer', '0003_auto_20210313_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='uploadedTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 7, 29, 18, 401782), null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='uploadedTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 7, 29, 18, 401305), null=True),
        ),
    ]
