# Generated by Django 3.1.7 on 2021-03-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songFileServer', '0005_auto_20210313_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='uploadedTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='uploadedTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='uploadedTime',
            field=models.DateTimeField(null=True),
        ),
    ]
