# Generated by Django 3.1.7 on 2021-03-13 08:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('songFileServer', '0006_auto_20210313_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='uploadedTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 8, 15, 57, 41004, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='uploadedTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 8, 15, 57, 40555, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='uploadedTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 8, 15, 57, 40207, tzinfo=utc), null=True),
        ),
    ]
