# Generated by Django 3.1.7 on 2021-03-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songFileServer', '0007_auto_20210313_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='uploadedTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='uploadedTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='uploadedTime',
            field=models.DateTimeField(null=True),
        ),
    ]
